name: Daily Commit Bot

on:
  schedule:
    - cron: '0 12 * * *'  # Run daily at 12:00 PM UTC
  workflow_dispatch:  # Allow manual trigger

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Run daily bot
      run: python bot.py
      
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff --quiet && git diff --staged --quiet || git commit -m "Daily advice update $(date +%Y-%m-%d)"
        git push 